services:
  tracker:
    build: .
    ports:
      - "8000:8000"
#    restart: unless-stopped
    environment:
      - SECRET_KEY=change-me-to-a-random-long-string
      - DATABASE_URL=sqlite:////data/plants.db
      - NOTIFY_EMAIL_TO=notify@example.com
      - NOTIFY_EMAIL_FROM=plants@example.com
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=you@example.com
      - SMTP_PASSWORD=replace-me
    volumes:
      - ./data:/data

  mailer:
    build: .
    environment:
      - SECRET_KEY=change-me-to-a-random-long-string
      - DATABASE_URL=sqlite:////data/plants.db
      - SEND_DUE_EMAIL=1
      - NOTIFY_EMAIL_TO=you@example.com
      - NOTIFY_EMAIL_FROM=you@example.com
      - SMTP_HOST=smtp.example.com
      - SMTP_PORT=587
      - SMTP_USER=you@example.com
      - SMTP_PASSWORD=replace-me
    volumes:
      - ./data:/data
    profiles: ["email"]
